use_frameworks!
#pod 'Neon','~> 0.0.3'
pod 'SnapKit'
pod 'SwiftyJSON'
#pod 'Rainbow'
pod 'SQLite.swift'
pod 'Alamofire'
pod 'Reachability'
pod 'HanekeSwift'
#pod 'GearRefreshControl'
#pod 'SlideMenuControllerSwift'
#pod 'Gecco'
pod 'PKHUD'
pod 'R.swift'
